modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="keychanger_shared"
version="1.0.0"
displayName="KindlyKlan Keys"
displayURL="https://discord.gg/kindlyklan"
credits="KeyManager para KindlyKlan"
authors="Javivi"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.keychanger_shared]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration
